### ISSUE TITLE
Definitely Typed for TypeScript need a PR according to helmet 2.0.0

### ISSUE THREAD

**Issue by juergenzimmermann** [helmetjs/hpkp#10]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/helmet/helmet.d.ts#L123 still has the 1.3 function declaration `publicKeyPins(...)` which is replaced in 2.0.0 by `hpkp(...)`.
@EvanHahn could you please provide another PR?

**Comment by EvanHahn** [comment]
Added a PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9162).

Closing this. See progress at the DefinitelyTyped PR.

**Comment by juergenzimmermann** [comment]
Thank you @EvanHahn
