### ISSUE TITLE
Definitely Typed for TypeScript@next needs a PR for the types-2.0 branch

### ISSUE THREAD

**Issue by juergenzimmermann** [helmetjs/hpkp#11]
The upcoming Typescript release will support the new `@types/` mechanism, so that .d.ts files can provided via `npm install` instead of the fragile `typings` (formerly `tsd`). For example:

```
npm install --save-dev @types/helmet
```

However, `@types` is using the types-2.0 branch and not the master branch of https://github.com/DefinitelyTyped/DefinitelyTyped:
- https://www.npmjs.com/package/@types/helmet
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/helmet/helmet.d.ts

Unfortunately the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9162 regarding  `hpkp(...)`  instead of `publicKeyPins(...)` is missing in the types-2.0 branch .

**Comment by EvanHahn** [comment]
This isn't directly an issue on this repo, but I'll still take a look.

Should I update https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9162 on another branch?

**Comment by juergenzimmermann** [comment]
@EvanHahn it would be great if you could provide https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9162 to the branch types-2.0 (in addition to the master branch):
* https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/helmet is covered by your PR
* https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/helmet also needs your PR

**Comment by EvanHahn** [comment]
@juergenzimmermann Would you be able to make that PR? It should, hopefully, be a matter of copying the code from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9162.

**Comment by EvanHahn** [comment]
@juergenzimmermann Is that a PR you're able to make?

**Comment by EvanHahn** [comment]
If anyone would like to help with this, feel free!

**Comment by EvanHahn** [comment]
I think this has been finished. I'm gonna close this issue.
