### ISSUE TITLE
Must require at least two pins, not just one.

### ISSUE THREAD

**Issue by tdelmas** [helmetjs/hpkp#3]
To be valid, an HPKP header mush pin : 
- at least one key of the current certificate chain.
- at least one key NOT in the current certificate chain (aka "Backup pin")
So any hpkp header with less than one pin can't be valid

https://tools.ietf.org/html/rfc7469#section-4.3

https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

**Comment by EvanHahn** [comment]
Is this just a matter of making sure that `sha256s` has an array of length 2+?

**Comment by tdelmas** [comment]
Basically, yes. 
And removing the sha256 option too, it is very confusing and can't produce a valid HPKP.
I know it's a small change, but I've seen a lot of people using invalid HPKP (with only one Pin).
I suggest that the error message explain why at least 2 pin are necessary.
If you prefer I can do a PR ?

**Comment by EvanHahn** [comment]
Sure! That'd let us remove a _lot_ of code, so that'd be great.
