### ISSUE TITLE
Allowing report-uri for both headers

### ISSUE THREAD

**Issue by konklone** [helmetjs/hpkp#7]
From the README:

> Specifying a report-uri changes the header from Public-Key-Pins to Public-Key-Pins-Report-Only.

That's not ideal, since a `report-uri` field [can be given to either header](https://developers.google.com/web/updates/2015/09/HPKP-reporting-with-chrome-46?hl=en), and it's useful under both circumstances.

**Comment by EvanHahn** [comment]
This is a good catch—totally a bug.

Are you comfortable with a breaking change? Or should I try to make this backwards-compatible? I realize anything goes with semver 0.x, but the library has been pretty stable. Maybe this could be the 1.0 release?

**Comment by konklone** [comment]
I'm comfortable with it, though I don't have this in production yet. =)

**Comment by EvanHahn** [comment]
@konklone I think it'd be good to make it backwards-compatible and then change it for 1.0. What do you think?

**Comment by konklone** [comment]
Sounds good to me! :+1:

**Comment by EvanHahn** [comment]
This should be fixed in `hpkp@0.3.0` and `helmet@0.15.0`. Thanks for reporting!
